# Generated by Django 3.2.5 on 2023-01-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_file',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_path', models.FileField(max_length=1024, null=True, upload_to='media/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='auth.user')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
