# Generated by Django 4.2.1 on 2023-05-21 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive_app', '0003_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile_picture',
            field=models.FileField(max_length=1024, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
