# Generated by Django 4.2.1 on 2023-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0004_familymember_profile_picture_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profile_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='media/'),
        ),
    ]
