# Generated by Django 4.2.7 on 2023-12-27 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive_app', '0007_rename_created_at_mediafile_date_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='user_uploaded',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UploadedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='archive_app.uploadedby'),
            preserve_default=False,
        ),
    ]
