# Generated by Django 4.2.1 on 2023-05-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_auto_20230129_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('birth_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Location of birth')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date of death')),
                ('marriage_date', models.DateField(blank=True, help_text='Date of Marriage with their partner.', null=True, verbose_name='Date of Marriage')),
                ('marriage_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Location of marriage')),
                ('marriage_date2', models.DateField(blank=True, help_text='Date of Marriage with their second partner.', null=True, verbose_name='Date of Marriage 2')),
                ('marriage_location2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Location of second marriage')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('father', models.ForeignKey(blank=True, help_text='ID of their father', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_father', to='archive_app.familymember', verbose_name='Father')),
                ('mother', models.ForeignKey(blank=True, help_text='ID of their mother', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_mother', to='archive_app.familymember', verbose_name='Mother')),
                ('partner', models.ForeignKey(blank=True, help_text='ID of their partner through marriage or who they have had children with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_partner', to='archive_app.familymember', verbose_name='Partner')),
                ('partner2', models.ForeignKey(blank=True, help_text='ID of a second partner through marriage or who they have had children with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_partner2', to='archive_app.familymember', verbose_name='Partner 2')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
