# Generated by Django 4.2.1 on 2023-05-28 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive_app', '0006_mediafile_created_at_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='created_at',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='user_uploaded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_path',
            field=models.FileField(max_length=128, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archive_app.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
